### PR TITLE
Added toggle dark and light theme on navigation

### PR DESCRIPTION
**Pull request by urmauur**
Solved issue #24 

- [x] update some color scheme
- [x] Add toggle theme on the navigation
- [x] Using different logo each theme
- [x] Update style about page 

Here the screenshots update

Screen Shot 2020-10-06 at 19 02 33

Screen Shot 2020-10-06 at 19 02 42

Screen Shot 2020-10-06 at 19 02 23

Screen Shot 2020-10-06 at 19 02 15

### CODE REVIEW

**Review by luisFilipePT — APPROVED** [review]
Great Job 👍

**Comment by luisFilipePT** [comment]
Thanks for your contribution! 🙌

@all-contributors please add @urmauur for code and design

**Comment by urmauur** [comment]
@luisFilipePT thanks for merge, btw can you update this PR with label `hacktoberfest-accepted`, take a look this https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by luisFilipePT** [comment]
> @luisFilipePT thanks for merge, btw can you update this PR with label `hacktoberfest-accepted`, take a look this https://hacktoberfest.digitalocean.com/hacktoberfest-update

You should not need that since this repo has the `hacktoberfest` topic, can you confirm if your contribution does not pop up here already if not let me know and I will add the tag.
https://hacktoberfest.digitalocean.com/profile

image

image

**Comment by urmauur** [comment]
> > @luisFilipePT thanks for merge, btw can you update this PR with label `hacktoberfest-accepted`, take a look this https://hacktoberfest.digitalocean.com/hacktoberfest-update
> 
> You should not need that since this repo has the `hacktoberfest` topic, can you confirm if your contribution does not pop up here already if not let me know and I will add the tag.
> https://hacktoberfest.digitalocean.com/profile
> 
> image

Yes sure, thank for clarify

Screen Shot 2020-10-07 at 13 17 00

**Comment by urmauur** [comment]
@luisFilipePT can you add this pr with `hacktoberfest-accepted`

**Pull request merged**
