### PR TITLE
Improve pagination

### PR DESCRIPTION
**Pull request by urmauur**
Hi @luisFilipePT sorry for taking a long time, need to cleanup some errand.

#29 solved issue

- [x] Added smooth scroll when the user next or back on pagination
- [x] Added Loader for home page and simple transition for all page 
- [x] Simple improvement pagination design adapt current theme
- [x] Make repo card and about us more readable
- [x] Update 404 page support theme dark and light

### CODE REVIEW

**Comment by urmauur** [comment]
@luisFilipePT  can you add this pr with `hacktoberfest-accepted`

**Comment by luisFilipePT** [comment]
@urmauur can you confirm pagination is working? I tested on the preview deploy and it's not working

**Comment by urmauur** [comment]
> @urmauur can you confirm pagination is working? I tested on the preview deploy and it's not working

seems like its broken, I'm on it now 🙏🏻

**Comment by urmauur** [comment]
@luisFilipePT can you check in the live version? https://commit-to-fight-covid.netlify.app on my side that broken

**Comment by urmauur** [comment]
@luisFilipePT updated MR

**Comment by luisFilipePT** [comment]
> @luisFilipePT can you check in the live version? https://commit-to-fight-covid.netlify.app on my side that broken

ok, now the pagination is working but we cannot search on typing due to the rate limit on github, we need to remove this and only search on enter or click on the icon.

**Comment by urmauur** [comment]
@luisFilipePT sorry for late reply, can you guys check this ?

**Comment by luisFilipePT** [comment]
> @luisFilipePT sorry for late reply, can you guys check this ?

It's still broken on the Preview, just keep typing and you should see it break, it cannot search on typing :/

**Comment by urmauur** [comment]
@luisFilipePT sorry my bad hehhe, hope this is fix all function, seems like somebody change search 🙏🏻

**Comment by urmauur** [comment]
Hi @luisFilipePT can you check this PR ?

**Pull request merged**
